layout: sidebar
style: dark
theme: null

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: huseyinn.deniz
  # keybase: your_username
  linkedin: hsyndeniz
  # mastodon: your_username
  medium: huseyindeniz
  stackoverflow: 11413042
  telegram: huseyindeniz
  twitter: hsyn__deniz
  # unsplash: your_username
  # vk: your_username
  website: http://huseyindeniz.me
  youtube: channel/UCnP1nljIl7KwDJK9KMPsAvQ

topics:
  - name: Web Development
    web_url: https://github.com/topics/web
    image_url: ./images/web2.png

  - name: Blockchain & Cryptocurrency
    web_url: https://github.com/topics/blockchain
    image_url: ./images/btc.png

  - name: Mobile Development
    web_url: https://github.com/topics/react-native
    image_url: ./images/mobile.png
